# Build in datasets

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = sns.load_dataset("titanic")

In [3]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
# save to excel 
df.to_excel('./Dataframes/titanic.xlsx', index = False)

In [5]:
# excel to python
df_titanic = pd.read_excel('./Dataframes/titanic_df.xlsx')

In [6]:
# read the csv file of microbial dataset
df_micro = pd.read_csv("C:/Users/BEST LAPTOP/Desktop/microbial.csv")

In [7]:
df_micro.head()

,bacteria,antibiotic,resistance,region,year,age,gender,prior_infection_site,intensive_care_metrics,cumulative_days_on_antibiotic,days_since_last_hospital_stay
0,P. aeruginosa,Vancomycin,83.740294,Africa,2018,52,F,Urinary,9,5,110
1,A. baumannii,Methicillin,54.298686,North America,2019,93,F,Urinary,9,0,99
2,K. pneumoniae,Methicillin,100.000000,Europe,2022,15,F,Respiratory,14,0,39
3,A. baumannii,Amoxicillin,45.493537,Asia,2018,72,M,NaN,14,10,365
4,A. baumannii,Amoxicillin,63.460719,Asia,2018,61,M,NaN,35,6,39

In [ ]:
#after moving the file from dekstop to project folder, move to dataframes folder
df_micro.to_csv('./Dataframes/microbial.csv')