# Pandas library

In [1]:
import pandas as pd  # first step

In [7]:
# import dataset by clipboarding
df = pd.read_clipboard()
df           # only used fro quick analysis

         contig   student      cov     len      gc
0    student0_1  student0  29.0114  255873  0.4995
1    student0_2  student0  31.5053  190425  0.5151
2    student0_3  student0  39.5121  149891  0.5077
3    student0_4  student0  37.9206  135958  0.5212
4    student0_5  student0  34.0143  121845  0.5204
5    student0_6  student0  30.4397  117759  0.5067
6    student0_7  student0  33.0765  114165  0.5210
7    student0_8  student0  40.6539  112487  0.5224
8    student0_9  student0  34.6739   97943  0.5203
9   student0_10  student0  34.1807   96681  0.5237
10  student0_11  student0  30.8479   93818  0.5095
11  student0_12  student0  34.0987   92190  0.5030
12  student0_13  student0  43.4598   88743  0.5262
13  student0_14  student0  36.3573   85173  0.5128
14  student0_15  student0  40.7952   83655  0.5075

### Importing datasets from excel

In [10]:
df_excel = pd.read_excel("../00_datasets/titanic_df.xlsx")
df_excel

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

## import csv files

In [11]:
df_csv = pd.read_csv("../00_datasets/microbial.csv")
df_csv

,Unnamed: 0,bacteria,antibiotic,resistance,region,year,age,gender,prior_infection_site,intensive_care_metrics,cumulative_days_on_antibiotic,days_since_last_hospital_stay
0,0,P. aeruginosa,Vancomycin,83.740294,Africa,2018,52,F,Urinary,9,5,110
1,1,A. baumannii,Methicillin,54.298686,North America,2019,93,F,Urinary,9,0,99
2,2,K. pneumoniae,Methicillin,100.000000,Europe,2022,15,F,Respiratory,14,0,39
3,3,A. baumannii,Amoxicillin,45.493537,Asia,2018,72,M,NaN,14,10,365
4,4,A. baumannii,Amoxicillin,63.460719,Asia,2018,61,M,NaN,35,6,39
...,...,...,...,...,...,...,...,...,...,...,...,...
3495,3495,E. coli,Ciprofloxacin,44.199565,Asia,2018,38,M,NaN,19,6,104
3496,3496,A. baumannii,Ciprofloxacin,50.912172,Africa,2021,3,M,Urinary,2,3,365
3497,3497,E. coli,Vancomycin,90.270913,Asia,2018,16,F,Urinary,2,2,159
3498,3498,E. coli,Amoxicillin,47.194067,North America,2019,94,F,Respiratory,4,2,65
3499,3499,E. coli,Amoxicillin,59.293169,Africa,2020,40,F,NaN,0,15,111