In [1]:
import pandas as pd

url = "https://www.worldometers.info/world-population/"

tables = pd.read_html(url)   # this will work after installing lxml packages

len(tables)
df = tables[2]

HTTPError: HTTP Error 403: Forbidden

In [2]:
import pandas as pd
from urllib.request import Request as req, urlopen  ## this is used to resolve the HTTP Error 403 , createS HTTP REQUEST

url = "https://en.wikipedia.org/wiki/World_population"

request= req(
    url,
    headers={"User-Agent": "for_webscraping_in_python/1.0"}  
)

html_url = urlopen(request)  #send request to wikipidia

tables = pd.read_html(html_url)

print(len(tables)) #print number of tables on web

df = tables[2] ## access the third tables on website
df

27

,Region,Density (inhabitants/km2),Population (millions),Most populous country,Most populous city (metropolitan area)
0,Asia,104.1,4641,"1,439,090,595 – India","13,515,000 – Tokyo Metropolis (37,400,000 – Gr..."
1,Africa,44.4,1340,"0,211,401,000 – Nigeria","09,500,000 – Cairo (20,076,000 – Greater Cairo)"
2,Europe,73.4,747,"0,146,171,000 – Russia, approx. 110 million in...","13,200,000 – Moscow (20,004,000 – Moscow metro..."
3,Latin America,24.1,653,"0,214,103,000 – Brazil","12,252,000 – São Paulo City (21,650,000 – São ..."
4,Northern America[note 1],14.9,368,"0,332,909,000 – United States","08,804,000 – New York City (23,582,649 – New Y..."
5,Oceania,5,42,"0,025,917,000 – Australia","05,367,000 – Sydney"
6,Antarctica,~0,0.004[90],N/A[note 2],"00,001,258 – McMurdo Station"

In [7]:
##save the table as dataframe
df.to_csv('../00_datasets/0.1_pandas_practice_datasets/region_data_population.csv', index=False)

In [9]:
## read csv file e.g iris data
import pandas as pd

iris_csv = pd.read_csv('https://gist.githubusercontent.com/netj/8836201/raw/')

iris_csv

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [10]:
## save iris datasets
iris_csv.to_csv('../00_datasets/0.1_pandas_practice_datasets/iris.csv', index=False)