# loc and iloc function
>**loc** is used to specify rows and column on the basis of **rows and column labels**\
>**iloc** is used to specify rows and columns on the basis of **integer index**

## loc function

In [1]:
import pandas as pd 

df = pd.read_csv('../00_datasets/microbial.csv')
df

,Unnamed: 0,bacteria,antibiotic,resistance,region,year,age,gender,prior_infection_site,intensive_care_metrics,cumulative_days_on_antibiotic,days_since_last_hospital_stay
0,0,P. aeruginosa,Vancomycin,83.740294,Africa,2018,52,F,Urinary,9,5,110
1,1,A. baumannii,Methicillin,54.298686,North America,2019,93,F,Urinary,9,0,99
2,2,K. pneumoniae,Methicillin,100.000000,Europe,2022,15,F,Respiratory,14,0,39
3,3,A. baumannii,Amoxicillin,45.493537,Asia,2018,72,M,NaN,14,10,365
4,4,A. baumannii,Amoxicillin,63.460719,Asia,2018,61,M,NaN,35,6,39
...,...,...,...,...,...,...,...,...,...,...,...,...
3495,3495,E. coli,Ciprofloxacin,44.199565,Asia,2018,38,M,NaN,19,6,104
3496,3496,A. baumannii,Ciprofloxacin,50.912172,Africa,2021,3,M,Urinary,2,3,365
3497,3497,E. coli,Vancomycin,90.270913,Asia,2018,16,F,Urinary,2,2,159
3498,3498,E. coli,Amoxicillin,47.194067,North America,2019,94,F,Respiratory,4,2,65
3499,3499,E. coli,Amoxicillin,59.293169,Africa,2020,40,F,NaN,0,15,111

In [2]:
# df[df["bacteria", "antibiotic", "resistance"]]   ## same as below
df.loc[0:5, "bacteria":"resistance"] # here value after ':' will be included because it is labeled base

        bacteria   antibiotic  resistance
0  P. aeruginosa   Vancomycin   83.740294
1   A. baumannii  Methicillin   54.298686
2  K. pneumoniae  Methicillin  100.000000
3   A. baumannii  Amoxicillin   45.493537
4   A. baumannii  Amoxicillin   63.460719
5      S. aureus   Penicillin   70.176834

In [8]:
# with negative indexing
# df.loc[-100:-50, 'bacteria' : 'resistance'] # this will not work because indexing is always [left to right]

df.loc[-50:100, 'bacteria' : 'resistance']

          bacteria   antibiotic  resistance
0    P. aeruginosa   Vancomycin   83.740294
1     A. baumannii  Methicillin   54.298686
2    K. pneumoniae  Methicillin  100.000000
3     A. baumannii  Amoxicillin   45.493537
4     A. baumannii  Amoxicillin   63.460719
..             ...          ...         ...
96   P. aeruginosa     Imipenem   96.362803
97    A. baumannii    Meropenem   29.085921
98         E. coli  Methicillin   29.155066
99    A. baumannii  Methicillin   75.560176
100   A. baumannii   Penicillin   27.899264

[101 rows x 3 columns]

## iloc function

In [10]:
df.iloc[0:5, 0:3]  #here the last one will excluded

   Unnamed: 0       bacteria   antibiotic
0           0  P. aeruginosa   Vancomycin
1           1   A. baumannii  Methicillin
2           2  K. pneumoniae  Methicillin
3           3   A. baumannii  Amoxicillin
4           4   A. baumannii  Amoxicillin